apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usuario-hpa
  namespace: usuario
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usuario-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65