apiVersion: v1
kind: Service
metadata:
  name: apim-entry-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: jogo
  ports:
    - name: http
      port: 80
      targetPort: 80